# Generated by Django 6.0 on 2026-01-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='memo',
            field=models.CharField(max_length=200),
        ),
    ]
