# Generated by Django 6.0 on 2026-01-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_record_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='memo',
            field=models.TextField(max_length=200),
        ),
    ]
