# Generated by Django 6.0 on 2026-01-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_record_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_min', models.IntegerField()),
                ('threshold_max', models.IntegerField(blank=True, null=True)),
                ('message_content', models.TextField()),
                ('needs_calculation', models.BooleanField(default=False)),
                ('max_reward_amount', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['threshold_min'],
            },
        ),
    ]
