# Generated by Django 6.0 on 2026-01-28 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_category', models.IntegerField(choices=[(0, 'お得情報'), (1, '日々のひと工夫'), (2, '失敗からの学び')])),
                ('title', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=1000)),
                ('status', models.IntegerField(choices=[(0, '下書き'), (1, '公開')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'topics',
                'ordering': ['-created_at'],
            },
        ),
    ]
