# Generated by Django 6.0 on 2026-02-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_comment_text_alter_topic_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.IntegerField(choices=[(0, '下書き'), (1, '公開')], default=0),
        ),
    ]
