# Generated by Django 6.0 on 2026-03-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_tag_topictag_topic_tags_topictag_uniq_topic_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='sequence',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
