# Generated by Django 6.0 on 2026-03-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_comment_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='sequence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
